// Generated by Dagger (https://dagger.dev).
package io.github.muntashirakon.music.mvp.presenter;

import io.github.muntashirakon.music.providers.interfaces.Repository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GenreDetailsPresenter_GenreDetailsPresenterImpl_Factory implements Factory<GenreDetailsPresenter.GenreDetailsPresenterImpl> {
  private final Provider<Repository> repositoryProvider;

  public GenreDetailsPresenter_GenreDetailsPresenterImpl_Factory(
      Provider<Repository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public GenreDetailsPresenter.GenreDetailsPresenterImpl get() {
    return newInstance(repositoryProvider.get());
  }

  public static GenreDetailsPresenter_GenreDetailsPresenterImpl_Factory create(
      Provider<Repository> repositoryProvider) {
    return new GenreDetailsPresenter_GenreDetailsPresenterImpl_Factory(repositoryProvider);
  }

  public static GenreDetailsPresenter.GenreDetailsPresenterImpl newInstance(Repository repository) {
    return new GenreDetailsPresenter.GenreDetailsPresenterImpl(repository);
  }
}
