// Generated by Dagger (https://dagger.dev).
package io.github.muntashirakon.music.mvp.presenter;

import io.github.muntashirakon.music.providers.interfaces.Repository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PlaylistSongsPresenter_PlaylistSongsPresenterImpl_Factory implements Factory<PlaylistSongsPresenter.PlaylistSongsPresenterImpl> {
  private final Provider<Repository> repositoryProvider;

  public PlaylistSongsPresenter_PlaylistSongsPresenterImpl_Factory(
      Provider<Repository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public PlaylistSongsPresenter.PlaylistSongsPresenterImpl get() {
    return newInstance(repositoryProvider.get());
  }

  public static PlaylistSongsPresenter_PlaylistSongsPresenterImpl_Factory create(
      Provider<Repository> repositoryProvider) {
    return new PlaylistSongsPresenter_PlaylistSongsPresenterImpl_Factory(repositoryProvider);
  }

  public static PlaylistSongsPresenter.PlaylistSongsPresenterImpl newInstance(
      Repository repository) {
    return new PlaylistSongsPresenter.PlaylistSongsPresenterImpl(repository);
  }
}
