// Generated by Dagger (https://dagger.dev).
package io.github.muntashirakon.music.mvp.presenter;

import io.github.muntashirakon.music.providers.interfaces.Repository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SearchPresenter_SearchPresenterImpl_Factory implements Factory<SearchPresenter.SearchPresenterImpl> {
  private final Provider<Repository> repositoryProvider;

  public SearchPresenter_SearchPresenterImpl_Factory(Provider<Repository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public SearchPresenter.SearchPresenterImpl get() {
    return newInstance(repositoryProvider.get());
  }

  public static SearchPresenter_SearchPresenterImpl_Factory create(
      Provider<Repository> repositoryProvider) {
    return new SearchPresenter_SearchPresenterImpl_Factory(repositoryProvider);
  }

  public static SearchPresenter.SearchPresenterImpl newInstance(Repository repository) {
    return new SearchPresenter.SearchPresenterImpl(repository);
  }
}
