name: ASS CI

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    name: Build, Test and Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle #

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: List all Gradle tasks (Debug)
        run: ./gradlew :app:tasks --all

      - name: Run Tests and Generate Jacoco Report
        run: ./gradlew :app:jacocoTestReport

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-report
          path: "**/build/reports/jacoco/jacocoTestReport/"